import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

import { ClerkProvider, SignedIn, SignedOut, SignIn} from '@clerk/nextjs'


// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={cn(
            'min-h-screen w-full bg-white text-black flex ',
            'inter',
            {
              'debug-screens': process.env.NODE_ENV === 'development'
            }
          )}
        >
          <>
            <div>
              <div className='p-8 w-full h-full flex'>
                <SignedOut>
                  <SignIn routing='hash' />
                </SignedOut>
                <SignedIn>
                  
                  {children}
                  
                </SignedIn>
              </div>
              <div></div>
            </div>
          </>
        </body>
      </html>
    </ClerkProvider>
  )
}
